server:
  port: 8080

spring:
  application:
    name: shop-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/online_shop}
    username: ${SPRING_DATASOURCE_USERNAME:online_shop}
    password: ${SPRING_DATASOURCE_PASSWORD:online_shop}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info
