server:
  port: 8081

spring:
  application:
    name: payment-service

payment:
  failure-rate: ${PAYMENT_FAILURE_RATE:0}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info
