-- liquibase formatted sql

-- changeset aberezhnoy:002-create-categories
CREATE TABLE categories
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    parent_id   INTEGER REFERENCES categories (id) ON DELETE CASCADE,
    description VARCHAR(1000) NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
