-- liquibase formatted sql

-- changeset aberezhnoy:004-create-products
CREATE TABLE products
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(250)    NOT NULL,
    price          NUMERIC(10, 2)  NOT NULL CHECK (price >= 0),
    stock_quantity INTEGER         NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    description    VARCHAR(2000),
    brand_id       INTEGER REFERENCES brands (id),
    category_id    INTEGER REFERENCES categories (id),
    created_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
