-- liquibase formatted sql

-- changeset aberezhnoy:005-create-carts-and-items
CREATE TABLE carts
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER   NOT NULL UNIQUE REFERENCES users (id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_items
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    INTEGER   NOT NULL REFERENCES carts (id) ON DELETE CASCADE,
    product_id INTEGER   NOT NULL REFERENCES products (id),
    quantity   INTEGER   NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (cart_id, product_id)
);
