-- liquibase formatted sql

-- changeset aberezhnoy:006-create-orders-and-items
CREATE TABLE orders
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER        NOT NULL REFERENCES users (id),
    total_amount NUMERIC(10, 2) NOT NULL CHECK (total_amount > 0),
    status       VARCHAR(20)    NOT NULL DEFAULT 'NEW'
        CHECK (status IN (
            'NEW',
            'PAYMENT_PENDING',
            'PAID',
            'PAYMENT_FAILED',
            'PAYMENT_CANCELLED',
            'PROCESSING',
            'SHIPPED',
            'DELIVERED',
            'CANCELLED'
        )),
    created_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              INTEGER        NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id            INTEGER        NOT NULL REFERENCES products (id),
    product_name_snapshot VARCHAR(250)   NOT NULL,
    price_at_time         NUMERIC(10, 2) NOT NULL CHECK (price_at_time > 0),
    quantity              INTEGER        NOT NULL CHECK (quantity > 0),
    line_total            NUMERIC(10, 2) NOT NULL CHECK (line_total > 0),
    created_at            TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
