-- liquibase formatted sql

-- changeset aberezhnoy:007-create-payments
CREATE TABLE payments
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       INTEGER        NOT NULL UNIQUE REFERENCES orders (id),
    amount         NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
    transaction_id VARCHAR(100),
    status         VARCHAR(20)    NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    payment_date   TIMESTAMP,
    payment_method VARCHAR(50)    NOT NULL,
    created_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
