-- liquibase formatted sql

-- changeset aberezhnoy:008-create-reviews
CREATE TABLE reviews
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER      NOT NULL REFERENCES products (id),
    user_id    INTEGER      NOT NULL REFERENCES users (id),
    comment    VARCHAR(2000),
    rating     INTEGER      NOT NULL CHECK (rating BETWEEN 1 AND 5),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (product_id, user_id)
);
